name=Boardoza Phoenix Board
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <eray.eroglu@boardoza.com>
sentence=Library for Boardoza Phoenix Board.
paragraph=This library provides an easy‑to‑use API for interfacing with the Boardoza Phoenix board. It handles I²C communication, performs precise measurements, and includes built‑in routines for various functionalities. With minimal dependencies and clear example sketches, it’s designed to help you integrate the Phoenix board quickly into any Arduino or PlatformIO project.
category=Boards
url=https://github.com/Boardoza/Boardoza_Phoenix_Board
architectures=*